### ISSUE TITLE
Valid

### ISSUE THREAD

**Issue by ge200012** [DSL-Lab/SwinGNN#1]
Hi, Have you ever tested the validity generated by datasets such as ego、grid、comminity、protein? There is a VNU metric in Degree for this type of non-molecular graph, but this metric is not present in this paper. How does this model perform on the VUN metric generated by non-molecular datasets.

**Comment by qiyan98** [comment]
Hi there,

We did notice that some papers adopt the VNU metrics. I believe you could use our model and checkpoints to generate graph samples and then use their metrics to obtain results. The metrics on graph generation are indeed open, and what we presented in the paper primarily followed the previous works for a better comparison (before VNU was used).
